# -*- coding: utf-8 -*-
# FYW 1323 schedule rows — EXACT verbatim transcription from the live site's
# index.html (schedule-table tbody), including <br>/<ul> structure and links.

rows = [
  dict(num="1", date="Wed. Aug. 26", topic="Welcome &amp; Genres", pre="Welcome! Syllabus review and Start of Semester Form.", notes=""),
  dict(num="2", date="Fri. Aug. 28", topic="Welcome &amp; Genres", pre="<strong>Starting Points</strong><ul><li>In-class: Diagnostic writing &mdash; &ldquo;What do you think a cult is?&rdquo; (handwritten)</li><li>In-class: Introduction to Perusall; annotation practice</li></ul>", notes=""),
  dict(num="3", date="Mon. Aug. 31", topic="The Power of Labels", pre="Reading: &ldquo;Understanding Genres&rdquo;", notes=""),
  dict(num="4", date="Wed. Sep. 2", topic="The Power of Labels", pre="&ldquo;Choosing and Refining Topics&rdquo;<br>In-Class Activity: The Tnevnoc Exercise", notes=""),
  dict(num="5", date="Fri. Sep. 4", topic="The Power of Labels", pre="Reading: David G. Bromley and Anson D. Shupe Jr., &ldquo;The Tnevnoc Cult&rdquo; (<em>Sociological Analysis</em>, 1979)", notes=""),
  dict(noclass="No Class &mdash; Labor Day", date="Mon. Sep. 7"),
  dict(num="6", date="Wed. Sep. 9", topic="Stasis Theory &amp; Definitions", pre="J.T. Richardson, &ldquo;Definitions of Cult: From Sociological-Technical to Popular-Negative&rdquo; (<em>Review of Religious Research</em>, 1993)", notes=""),
  dict(num="7", date="Fri. Sep. 11", topic="Stasis Theory &amp; Definitions", pre="Reading: &ldquo;How Stasis Theory Helps You to Write a Better Paper&rdquo;<br>AND Rebecca Moore, &ldquo;The Brainwashing Myth&rdquo;<br>In-Class Writing: Categorizing cult debates using Stasis Theory (handwritten)", notes=""),
  dict(num="8", date="Mon. Sep. 14", topic="X-Ray Reading &amp; Brainwashing", pre="&ldquo;X-Ray Reading / Reading Better to Write Better&rdquo;<br>&ldquo;Bad Research Questions&rdquo;", notes=""),
  dict(num="9", date="Wed. Sep. 16", topic="X-Ray Reading &amp; Brainwashing", pre="Barker, Eileen. &ldquo;Introduction,&rdquo; <em>The Making of a Moonie: Choice Or Brainwashing?</em>", notes="<mark>Research Question Due in Class</mark>"),
  dict(num="10", date="Fri. Sep. 18", topic="X-Ray Reading &amp; Brainwashing", pre="Evans, &ldquo;Introduction: Religion Unrecognized,&rdquo; from <em>Move: An American Religion</em><br>In-Class Writing: X-raying Barker&rsquo;s argument (handwritten, 30 minutes)", notes=""),
  dict(num="11", date="Mon. Sep. 21", topic="The Scholarly Dinner Table", pre="<strong>Library Session &amp; Source Evaluation</strong><br>Mike Caulfield, &ldquo;Four Moves and a Habit&rdquo; (from <em>Web Literacy for Student Fact-Checkers</em>)<br>MEET IN LIBRARY: Session with Library Research<ul><li>Introduction to library databases; finding scholarly sources on cults</li><li>Assignment: Find 3 potential sources for your research topic; bring citations to Wednesday</li></ul>", notes=""),
  dict(num="12", date="Wed. Sep. 23", topic="The Scholarly Dinner Table", pre="In-Class Workshop: Annotated bibliography entries (bring laptops)<ul><li>In-class: Evaluating source credibility, write 2 annotated bibliography entries in class</li></ul>", notes=""),
  dict(num="13", date="Fri. Sep. 25", topic="The Scholarly Dinner Table", pre="In-Class Workshop: Annotated bibliography entries (bring laptops)<ul><li>Write 2 more annotated bibliography entries in class</li></ul>", notes="<mark>DUE: Annotated Bibliography (min. 5 scholarly sources) by 11:59pm to Moodle</mark>"),
  dict(num="14", date="Mon. Sep. 28", topic="Case Study &mdash; Heaven&rsquo;s Gate", pre="Rousselet et al., &ldquo;Cult Membership: What Factors Contribute to Joining or Leaving?&rdquo; (<em>Psychiatry Research</em>, 2017)", notes=""),
  dict(num="15", date="Wed. Sep. 30", topic="Case Study &mdash; Heaven&rsquo;s Gate", pre="Benjamin E. Zeller, &ldquo;Extraterrestrial Biblical Hermeneutics and the Making of Heaven&rsquo;s Gate&rdquo; (<em>Nova Religio</em>, 2010)", notes=""),
  dict(num="16", date="Fri. Oct. 2", topic="Case Study &mdash; Heaven&rsquo;s Gate", pre="Pre-class listening assignment: <em>Heaven&rsquo;s Gate</em> Podcast (Glynn Washington), Episode 1<ul><li>In-class: HBO documentary <em>Heaven&rsquo;s Gate: The Cult of Cults</em> (selections)</li><li>Writing and discussion comparing media vs. academic tone</li></ul>", notes="<mark>DUE: Background section by 11:59pm to Moodle</mark>"),
  dict(num="17", date="Mon. Oct. 5", topic="Case Study &mdash; Scientology", pre="Westbrook, <em>Handbook of Scientology</em> &ldquo;Researching Scientology and Scientologists in the United States: Methods and Conclusions&rdquo;", notes=""),
  dict(num="18", date="Wed. Oct. 7", topic="Case Study &mdash; Scientology", pre="Gerald Graff, &ldquo;They Say / I Say&rdquo;: The Moves That Matter in Academic Writing, with readings<br>In class: Selections from <em>Going Clear</em>", notes=""),
  dict(num="19", date="Fri. Oct. 9", topic="Case Study &mdash; Scientology", pre="In-Class Writing and Discussion: Comparing scholarly article (Monday) with documentary (Wednesday)<ul><li>What does each source emphasize? What gets left out?</li></ul>", notes="<mark>DUE: Methodology and Significance sections by 11:59pm to Moodle</mark>"),
  dict(noclass="No Class &mdash; Fall Break", date="Mon. Oct. 12"),
  dict(num="20", date="Wed. Oct. 14", topic="Fall Break &amp; Abstracts", pre='<a href="https://patthomson.net/2022/09/19/academic-writing-from-tiny-text-to-road-map/">&ldquo;All About Abstracts&rdquo;</a> (Focus-Locate-Report-Argue format)<ul><li>In-class: Decoding sample abstracts</li></ul>', notes=""),
  dict(num="21", date="Fri. Oct. 16", topic="Fall Break &amp; Abstracts", pre="In-Class Writing: Drafting the Midterm Abstract", notes="<mark>DUE: Abstract and Compiled Proposal Draft Due by 11:59pm to Moodle</mark>"),
  dict(num="22", date="Mon. Oct. 19", topic="Review, Revise, Reflect", pre="In-Class Peer Review of Proposals", notes=""),
  dict(num="23", date="Wed. Oct. 21", topic="Review, Revise, Reflect", pre="In-class AI Workshop #1: AI as &ldquo;Scholarly Conversation Partner&rdquo;<br>Bring laptop", notes=""),
  dict(num="24", date="Fri. Oct. 23", topic="Review, Revise, Reflect", pre="In-class reflective writing and discussion", notes="<mark>DUE: Research Proposal (Midterm Assignment) final draft by 11:59pm to Moodle</mark>"),
  dict(num="25", date="Mon. Oct. 26", topic="", pre="No class &mdash; out of class consultations with Dr. Montrose", notes=""),
  dict(num="26", date="Wed. Oct. 28", topic="", pre="No class &mdash; out of class consultations with Dr. Montrose", notes=""),
  dict(num="27", date="Fri. Oct. 30", topic="", pre="No class &mdash; out of class consultations with Dr. Montrose", notes="<mark>DUE: By 11:59pm, email Dr. Montrose a summary of your notes from the meeting and submit your action plan with next steps for your paper.</mark>"),
  dict(num="28", date="Mon. Nov. 2", topic="", pre="Case Study: NXIVM (reading TBD)", notes=""),
  dict(num="29", date="Wed. Nov. 4", topic="", pre="Anne Lamott, &ldquo;Shitty First Drafts&rdquo; (from <em>Bird by Bird</em>)", notes=""),
  dict(num="30", date="Fri. Nov. 6", topic="", pre="", notes=""),
  dict(num="31", date="Mon. Nov. 9", topic="", pre="", notes=""),
  dict(num="32", date="Wed. Nov. 11", topic="", pre="", notes=""),
  dict(num="33", date="Fri. Nov. 13", topic="", pre="", notes=""),
  dict(num="34", date="Mon. Nov. 16", topic="", pre="", notes=""),
  dict(num="35", date="Wed. Nov. 18", topic="", pre="", notes=""),
  dict(noclass="No Class &mdash; Dr. Montrose is at a conference. Work on your final paper.", date="Fri. Nov. 20"),
  dict(noclass="No Class &mdash; Dr. Montrose is at a conference. Work on your final paper.", date="Mon. Nov. 23"),
  dict(noclass="No Class &mdash; Thanksgiving Break", date="Wed. Nov. 25"),
  dict(noclass="No Class &mdash; Thanksgiving Break", date="Fri. Nov. 27"),
  dict(num="36", date="Mon. Nov. 30", topic="", pre="", notes=""),
  dict(num="37", date="Wed. Dec. 2", topic="", pre="", notes=""),
  dict(num="38", date="Fri. Dec. 4", topic="", pre="", notes=""),
  dict(num="39", date="Mon. Dec. 7", topic="Peer Review", pre="", notes=""),
  dict(noclass="<mark>Final Paper Due &mdash; 12:00 PM, uploaded to Moodle</mark>", date="Tue. Dec. 15"),
]
